---
title: "农业废弃物制储氢材料论文复现报告"
author: "黄娇"
date: "2026-04-09"
format:
  html:
    toc: true
    code-fold: true
---

# 一、数据准备
```{r}
set.seed(123)

group <- factor(c("UTL0", "UTL1", "UTL2", "UTL3",
                  "OP0",  "OP1",  "OP2",  "OP3"))

H2_excess <- c(0, 4.44, 4.83, 5.29,
               0, 4.06, 4.78, 5.24)

BET_SSA <- c(5, 2008, 2378, 2814,
             3, 1700, 2218, 2417)

dat <- data.frame(group, H2_excess, BET_SSA)
dat
library(ggplot2)
library(dplyr)

mean_data <- dat %>%
  group_by(group) %>%
  summarise(mean_H2 = mean(H2_excess))

ggplot(dat, aes(x = group, y = H2_excess, fill = group)) +
  geom_boxplot(width = 0.6, outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.2, size = 2.5, color = "black") +
  geom_text(data = mean_data,
            aes(label = sprintf("%.2f", mean_H2)),
            vjust = -0.8, size = 4, fontface = "bold") +
  labs(title = "不同样品高压储氢过量值对比",
       x = "样品类型",
       y = "储氢量 (wt%)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")
        cor_result <- cor.test(dat$BET_SSA, dat$H2_excess, method = "kendall")
cor_result

library(ggplot2)
library(dplyr)

mean_data <- dat %>%
  group_by(group) %>%
  summarise(mean_H2 = mean(H2_excess))

ggplot(dat, aes(x = group, y = H2_excess, fill = group)) +
  geom_boxplot(width = 0.6, outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.2, size = 2.5, color = "black") +
  geom_text(data = mean_data,
            aes(label = sprintf("%.2f", mean_H2)),
            vjust = -0.8, size = 4, fontface = "bold") +
  labs(title = "不同样品高压储氢过量值对比",
       x = "样品类型",
       y = "储氢量 (wt%)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")

        cor_result <- cor.test(dat$BET_SSA, dat$H2_excess, method = "kendall")
cor_result

